# Generated by Django 5.2.6 on 2025-09-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_key_picks_per_week', models.PositiveIntegerField(default=1)),
                ('points_per_correct_pick', models.IntegerField(default=1)),
                ('points_per_key_pick', models.IntegerField(default=2)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cfb.season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=128)),
                ('logo_url', models.URLField(blank=True)),
                ('record_wins', models.PositiveIntegerField(default=0)),
                ('record_losses', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cfb.season')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('opening_home_spread', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('opening_away_spread', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('opening_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_home_spread', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_away_spread', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('clock', models.CharField(blank=True, max_length=16)),
                ('is_final', models.BooleanField(default=False)),
                ('is_selected_for_pickem', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='cfb.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='cfb.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='cfb.team')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_key_pick', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='cfb.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
                ('picked_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='cfb.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('game', 'user')},
            },
        ),
    ]
