# Generated by Django 5.2.6 on 2025-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
