# Generated by Django 5.2.7 on 2025-10-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
