# Generated by Django 5.2.7 on 2025-10-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0002_alter_team_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='team',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='team',
            name='state',
        ),
        migrations.RemoveField(
            model_name='team',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='venue_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='alt_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
