# Generated by Django 5.2.6 on 2025-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0002_game_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='team',
            name='cfbd_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='espn_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
