# Generated by Django 5.2.6 on 2025-09-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0003_team_abbreviation_team_cfbd_id_team_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alt_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='team',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
