# Generated by Django 5.2.7 on 2025-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0003_remove_team_city_remove_team_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text='Venue or location name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
