# Generated by Django 5.2.6 on 2025-10-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0004_team_alt_color_team_city_team_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='cfb.game')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['game', '-timestamp'], name='cfb_gamespr_game_id_d2a008_idx')],
            },
        ),
    ]
