# Generated by Django 5.2.7 on 2025-10-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0004_alter_location_city_alter_location_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('season_type', models.CharField(default='regular', help_text='regular, postseason, etc.', max_length=32)),
                ('poll', models.CharField(help_text='Poll name (e.g., AP Top 25, Coaches Poll)', max_length=64)),
                ('rank', models.PositiveIntegerField()),
                ('first_place_votes', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='cfb.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='cfb.team')),
            ],
            options={
                'ordering': ['season', 'week', 'poll', 'rank'],
                'indexes': [models.Index(fields=['season', 'week', 'poll'], name='cfb_ranking_season__0738cf_idx'), models.Index(fields=['team', 'season'], name='cfb_ranking_team_id_f90c8e_idx')],
                'unique_together': {('season', 'week', 'season_type', 'team', 'poll')},
            },
        ),
    ]
