# Generated by Django 5.2.6 on 2025-10-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0005_gamespread'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pick_away_spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pick_home_spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pick_spread_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
