# Generated by Django 5.2.7 on 2025-10-14 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0006_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['season', 'number']},
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='cfb_game_season__6dd8b3_idx',
            old_name='cfb_game_season__e1bcd6_idx',
        ),
        migrations.RenameIndex(
            model_name='ranking',
            new_name='cfb_ranking_season__75741c_idx',
            old_name='cfb_ranking_season__0738cf_idx',
        ),
        migrations.AddField(
            model_name='gamespread',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='cfb.week'),
        ),
        migrations.AddField(
            model_name='week',
            name='season_type',
            field=models.CharField(default='regular', help_text='regular, postseason, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='cfb.week'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='cfb.week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('season', 'number', 'season_type')},
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['season', 'number', 'season_type'], name='cfb_week_season__cf0a50_idx'),
        ),
    ]
