# Generated by Django 5.2.7 on 2025-10-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0007_alter_week_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerules',
            name='against_the_spread_enabled',
            field=models.BooleanField(default=True, help_text='Allow users to pick against the spread'),
        ),
    ]
