# Generated by Django 5.2.6 on 2025-10-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0008_leaguegame_pick_league_and_more'),
    ]

    operations = [
        # Remove league-specific fields from Game model
        # These are now handled by LeagueGame
        migrations.RemoveField(
            model_name='game',
            name='is_selected_for_pickem',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pick_home_spread',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pick_away_spread',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pick_spread_locked_at',
        ),
    ]

