# Generated by Django 5.2.7 on 2025-10-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0008_leaguerules_against_the_spread_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_total',
            new_name='current_over_under',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opening_total',
            new_name='opening_over_under',
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='tiebreaker',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Correct Key Picks (if enabled)'), (2, 'Total Points'), (3, 'Correct Picks')], default=0, help_text='Tiebreaker rule'),
        ),
        migrations.AlterField(
            model_name='leaguerules',
            name='spread_lock_weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day of the week when spreads lock in place if against the spread is enabled'),
        ),
        migrations.CreateModel(
            name='GameOverUnder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_under', models.DecimalField(decimal_places=1, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_unders', to='cfb.game')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over_unders', to='cfb.week')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['game', '-timestamp'], name='cfb_gameove_game_id_1adaa1_idx')],
            },
        ),
    ]
