# Generated by Django 5.2.7 on 2025-10-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0009_rename_current_total_game_current_over_under_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguegame',
            name='is_total_points_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pick',
            name='is_total_points_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pick',
            name='points_guess',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GameOverUnder',
        ),
    ]
