# Generated by Django 5.2.7 on 2025-10-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0010_leaguegame_is_total_points_game_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamespread',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Game Spread', 'verbose_name_plural': 'Game Spreads'},
        ),
        migrations.AlterModelOptions(
            name='leaguegame',
            options={'ordering': ['game__kickoff'], 'verbose_name': 'League Game', 'verbose_name_plural': 'League Games'},
        ),
        migrations.AlterModelOptions(
            name='leaguemembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'League Membership', 'verbose_name_plural': 'League Memberships'},
        ),
        migrations.AlterModelOptions(
            name='leaguerules',
            options={'ordering': ['-season__year'], 'verbose_name': 'League Rule', 'verbose_name_plural': 'League Rules'},
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='force_hooks',
            field=models.BooleanField(default=False, help_text='Force users to pick with hooks'),
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
