# Generated by Django 5.2.7 on 2025-10-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0011_alter_gamespread_options_alter_leaguegame_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('through_week', models.PositiveIntegerField(default=0)),
                ('picks_made', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('correct_key', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to='cfb.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to='cfb.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'season'], name='cfb_members_league__d275fb_idx'), models.Index(fields=['league', 'points'], name='cfb_members_league__30ef14_idx')],
                'unique_together': {('league', 'season', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemberWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picks_made', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('correct_key', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('points_guess', models.IntegerField(blank=True, null=True)),
                ('points_actual', models.IntegerField(blank=True, null=True)),
                ('tiebreak_abs_diff', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_weeks', to='cfb.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_weeks', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_weeks', to='cfb.week')),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'week'], name='cfb_memberw_league__e3fde4_idx'), models.Index(fields=['league', 'points'], name='cfb_memberw_league__e412aa_idx')],
                'unique_together': {('league', 'week', 'user')},
            },
        ),
    ]
