# Generated by Django 5.2.7 on 2025-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0012_memberseason_memberweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberseason',
            name='incorrect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberweek',
            name='incorrect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberweek',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
