# Generated by Django 5.2.7 on 2025-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0013_memberseason_incorrect_memberseason_ties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerules',
            name='drop_weeks',
            field=models.IntegerField(default=0, help_text='Number of weeks to drop from the season'),
        ),
    ]
