# Generated by Django 5.2.7 on 2025-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0014_leaguerules_drop_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberseason',
            name='correct_dropped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='correct_key_dropped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='incorrect_dropped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='picks_made_dropped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='points_dropped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberseason',
            name='ties_dropped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
