# Generated by Django 5.2.7 on 2025-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0015_memberseason_correct_dropped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberseason',
            name='rank_with_drops',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
