# Generated by Django 5.2.7 on 2025-11-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0016_memberseason_rank_with_drops'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='cfb.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='cfb.team')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'team'], name='cfb_teamsta_season__691f25_idx'), models.Index(fields=['season', 'stat'], name='cfb_teamsta_season__9a94b4_idx')],
                'unique_together': {('season', 'team', 'stat')},
            },
        ),
    ]
