# Generated by Django 5.2.7 on 2025-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfb", "0016_memberseason_rank_with_drops"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="finalized_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the game was first finalized",
                null=True,
            ),
        ),
    ]
