# Generated by Django 5.2.7 on 2025-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0017_teamstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerules',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Entry fee for the league', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='season_payout_last_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional: Percentage of season payout allocated to last place', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='season_payout_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage of total pool allocated to season winners', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='season_payout_structure',
            field=models.JSONField(blank=True, default=dict, help_text="JSON structure defining percentage payout for each season position (e.g., {'1': 60, '2': 30, '3': 10})"),
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='weekly_payout_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage of total pool allocated to weekly winners', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='weekly_payout_structure',
            field=models.JSONField(blank=True, default=dict, help_text="JSON structure defining percentage payout for each weekly position (e.g., {'1': 50, '2': 30, '3': 20})"),
        ),
    ]
