# Generated by Django 5.2.7 on 2026-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0018_leaguerules_entry_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive members cannot make picks and are excluded from standings.'),
        ),
    ]
