# Generated by Django 5.2.7 on 2026-08-16

from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.utils.crypto import get_random_string


def hash_existing_league_passwords(apps, schema_editor):
    League = apps.get_model("cfb", "League")
    for league in League.objects.all():
        league.join_password = make_password(get_random_string(20))
        league.save(update_fields=["join_password"])


class Migration(migrations.Migration):

    dependencies = [
        ("cfb", "0019_leaguemembership_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="invite_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="league",
            name="join_password",
            field=models.CharField(
                default="",
                help_text="Hashed password required to join this league.",
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(hash_existing_league_passwords, migrations.RunPython.noop),
    ]
