# Generated by Django 5.2.7 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfb", "0020_league_join_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="season_opt_in_required",
            field=models.BooleanField(
                default=False,
                help_text="Set when a new season starts. Owner must open the league for the year before members can opt in.",
            ),
        ),
    ]
