# Generated by Django 5.2.7 on 2026-09-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0022_league_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemembership',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether this member has paid the league entry fee.'),
        ),
    ]
