# Generated by Django 5.2.7 on 2026-09-01 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_membership_paid_to_season_payment(apps, schema_editor):
    LeagueMembership = apps.get_model("cfb", "LeagueMembership")
    MemberSeasonPayment = apps.get_model("cfb", "MemberSeasonPayment")
    Season = apps.get_model("cfb", "Season")

    active_season = Season.objects.filter(is_active=True).first()
    if not active_season:
        return

    for membership in LeagueMembership.objects.filter(paid=True):
        MemberSeasonPayment.objects.get_or_create(
            league_id=membership.league_id,
            season_id=active_season.id,
            user_id=membership.user_id,
            defaults={"paid": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cfb", "0023_leaguemembership_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSeasonPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this member has paid the season entry fee.",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_payments",
                        to="cfb.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_payments",
                        to="cfb.season",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Season Payment",
                "verbose_name_plural": "Member Season Payments",
                "unique_together": {("league", "season", "user")},
            },
        ),
        migrations.RunPython(migrate_membership_paid_to_season_payment, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="leaguemembership",
            name="paid",
        ),
    ]
