# Generated by Django 5.2.7 on 2026-09-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0024_member_season_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='possession',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
