# Generated by Django 5.2.7 on 2026-09-13 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0029_leaguerules_season_end_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('kind', models.CharField(choices=[('one_time', 'One-time'), ('persistent', 'Persistent')], default='one_time', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional. If set, hidden until this time.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional. If set, hidden after this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_league_announcements', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='cfb.league')),
            ],
            options={
                'verbose_name': 'League Announcement',
                'verbose_name_plural': 'League Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='cfb.leagueannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Dismissal',
                'verbose_name_plural': 'Announcement Dismissals',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leagueannouncement',
            index=models.Index(fields=['league', 'is_active'], name='cfb_leaguea_league__c6153d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userannouncementdismissal',
            unique_together={('announcement', 'user')},
        ),
    ]
