# Generated by Django 5.2.7 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0030_league_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberseasonpayment',
            name='paid_receipt_dismissed',
            field=models.BooleanField(default=False, help_text="Whether the user dismissed the 'entry fee received' home alert for this season."),
        ),
    ]
