# Generated by Django 5.2.7 on 2026-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0031_memberseasonpayment_paid_receipt_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerules',
            name='season_payout_last_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional: Percentage of season payout for most incorrect picks (drop weeks applied; missed games do not count as incorrect)', max_digits=5, null=True),
        ),
    ]
